donza/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("management/", include("management.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    re_path(
        "",
        RedirectView.as_view(pattern_name="management:index", permanent=False),
    ),
]

management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path("leden/", views.LidTableView.as_view(), name="leden"),
    path("leden/<int:pk>/", views.LidEditView.as_view(), name="lid"),
    path(
        "leden/<int:pk>/verwijder", views.verwijder_lid, name="verwijder_lid"
    ),
    path(
        "lid_modal/<int:pk>/", views.LidModalView.as_view(), name="lid_modal"
    ),
    path("leden/verwerk/", views.verwerk_leden, name="verwerk_leden"),
    path("leden/nieuw/", views.LidNewView.as_view(), name="nieuw_lid"),
    path("ouder/new/", views.create_ouder, name="new_ouder"),
    path(
        "betalingen/stuur_mail/<int:pk>/",
        views.stuur_mail,
        name="betalingen_mail",
    ),
    path(
        "betalingen/her_mail/<int:pk>/",
        views.herinnering_mail,
        name="herinnering_mail",
    ),
    path(
        "betalingen/bevestiging/<int:pk>/",
        views.bevestig_mail,
        name="bevestig_mail",
    ),
    path("betalingen/", views.BetalingTableView.as_view(), name="betalingen"),
    path("mails/", views.MailView.as_view(), name="mails"),
    path("mails/groep_mail/", views.groep_mail, name="groep_mail"),
    path("fetch_mail/", views.fetch_mail, name="fetch_mail"),
    path(
        "change_seizoen/<int:pk>/", views.change_seizoen, name="change_seizoen"
    ),
    path("", views.IndexView.as_view(), name="index"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
app_name = "management"

handler500 = views.handler500

management/models.py
import logging
from datetime import datetime

from django.core.exceptions import ValidationError
from django.db import models
from localflavor.generic.models import IBANField
from phonenumber_field.modelfields import PhoneNumberField

MAN = "m"
VROUW = "v"
ANDER = "x"
GEMENGD = "g"
LID_GESLACHT_CHOICES = [
    (MAN, "Man"),
    (VROUW, "Vrouw"),
    (ANDER, "Verkies niet te zeggen"),
]
PLOEG_GESLACHT_CHOICES = [
    (MAN, "Man"),
    (VROUW, "Vrouw"),
    (GEMENGD, "Gemengd"),
]

logger = logging.getLogger(__name__)


class Functie(models.Model):
    functie_id = models.AutoField(primary_key=True)
    functie = models.CharField(max_length=50)
    objects = models.Manager()

    def __str__(self):
        return self.functie


class Ouder(models.Model):
    ouder_id = models.AutoField(primary_key=True)
    gsmnummer = PhoneNumberField()
    voornaam = models.CharField(max_length=20)
    familienaam = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    objects = models.Manager()

    def __str__(self):
        return self.voornaam + " " + self.familienaam


class Seizoen(models.Model):
    seizoen_id = models.AutoField(primary_key=True)
    naam = models.CharField(max_length=20)
    startdatum = models.DateField()
    einddatum = models.DateField()
    bezig = models.BooleanField()
    objects = models.Manager()

    def __str__(self):
        return "({}-{})".format(self.startdatum.year, self.einddatum.year)


class PloegKenmerk(models.Model):
    kenmerk = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.kenmerk


class Ploeg(models.Model):
    ploeg_id = models.AutoField(primary_key=True)
    seizoen = models.ForeignKey("management.Seizoen", on_delete=models.CASCADE)
    naam = models.CharField(max_length=20)
    korte_naam = models.CharField(max_length=5)
    min_geboortejaar = models.IntegerField(null=True, blank=True)
    max_geboortejaar = models.IntegerField()
    uitzonderings_geboortejaar = models.IntegerField()
    geslacht = models.CharField(
        max_length=2, choices=PLOEG_GESLACHT_CHOICES, default=MAN
    )
    lidgeldklasse = models.ForeignKey(
        "management.LidgeldKlasse",
        default=None,
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
    )
    objects = models.Manager()
    kenmerken = models.ManyToManyField(PloegKenmerk, blank=True)

    def __str__(self):
        return "({}) {} ({}-{})".format(
            self.geslacht,
            self.naam,
            self.seizoen.startdatum.year,
            self.seizoen.einddatum.year,
        )


class PloegLid(models.Model):
    ploeg = models.ForeignKey("management.Ploeg", on_delete=models.CASCADE)
    lid = models.ForeignKey("management.Lid", on_delete=models.CASCADE)
    functie = models.ForeignKey("management.Functie", on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return "Ploeg: {} -- Lid: {} ({})".format(
            self.ploeg, self.lid, self.functie
        )

    def clean(self) -> None:
        """
        Clean method. Called during validation of the model during instance creation.
        Overwritten to implement custom validation logic.

        Raises:
            ValidationError: Raises a ValidationError when validation fails
        """
        if (
            self.ploeg.geslacht != "g"
            and self.ploeg.geslacht != self.lid.geslacht
        ):
            raise ValidationError(
                f"Lid {self.lid.voornaam} {self.lid.familienaam} kan \
                    niet in ploeg {self.ploeg.naam} zitten, aangezien \
                        het lid het verkeerde geslacht heeft."
            )

        if (
            not self.ploeg.min_geboortejaar
            <= self.lid.geboortedatum.year
            <= self.ploeg.uitzonderings_geboortejaar
        ):
            raise ValidationError(
                f"Lid {self.lid.voornaam + ' ' + self.lid.familienaam} kan \
                    niet in ploeg {self.ploeg.naam} zitten, aangezien het \
                        lid niet de correcte leeftijd heeft."
            )

    def save(self, *args, **kwargs):
        """
        Overwrite the save method to include a full validation

        Returns:
            _type_: _description_
        """
        self.full_clean()
        return super().save(*args, **kwargs)


class Lid(models.Model):
    club_id = models.AutoField(primary_key=True)
    voornaam = models.CharField(max_length=20)
    familienaam = models.CharField(max_length=50)
    geslacht = models.CharField(
        max_length=1, choices=LID_GESLACHT_CHOICES, default=MAN
    )
    sportief_lid = models.BooleanField(default=False)
    betalend_lid = models.BooleanField(default=False)
    actief_lid = models.BooleanField(default=True)
    straatnaam_en_huisnummer = models.CharField(max_length=50)
    postcode = models.IntegerField()
    gemeente = models.CharField(max_length=50)
    geboortedatum = models.DateField(null=True)
    gsmnummer = PhoneNumberField(null=True, blank=True)
    moeder = models.ForeignKey(
        "management.Ouder",
        related_name="moeder",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    vader = models.ForeignKey(
        "management.Ouder",
        related_name="vader",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    email = models.EmailField(max_length=254, null=True, blank=True)
    gescheiden_ouders = models.BooleanField(default=False)
    extra_informatie = models.CharField(default="", max_length=500, blank=True)
    rekeningnummer = IBANField(null=True, blank=True)
    lidnummer_vbl = models.IntegerField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    functies = models.ManyToManyField(Functie, blank=True)
    familieleden = models.ManyToManyField("self", blank=True)
    facturatie = models.BooleanField(default=False)
    afbetaling = models.BooleanField(default=False)
    uid = models.DecimalField(
        max_digits=10,
        decimal_places=0,
        unique=True,
        blank=True,
        null=True,
    )
    objects = models.Manager()

    def __str__(self):
        return f"{self.voornaam} {self.familienaam} ({self.lidnummer_vbl})"


class Betaling(models.Model):
    origineel_bedrag = models.FloatField()
    afgelost_bedrag = models.FloatField()
    lid = models.ForeignKey("management.Lid", on_delete=models.CASCADE)
    seizoen = models.ForeignKey("management.Seizoen", on_delete=models.CASCADE)
    mails_verstuurd = models.CharField(
        max_length=500, default="", null=True, blank=True
    )
    mededeling = models.CharField(max_length=20)
    type = models.CharField(max_length=20)
    # TODO: make this a dynamic field
    status = models.CharField(max_length=20)
    aflossingen = models.CharField(max_length=500, default="")
    objects = models.Manager()

    def __str__(self):
        return "{}: {}".format(self.lid, self.mededeling)

    def los_af(self, aflossing):
        """
        Los een betaling af
        :param aflossing:
        :return:
        """
        afl_nummers = self.aflossingen.split(",")
        datum = datetime.strftime(
            datetime.strptime(aflossing["datum"], "%d/%m/%Y"), "%d/%m/%Y"
        )

        if datum not in afl_nummers:
            bedrag = aflossing["credit"].replace(",", ".")
            self.afgelost_bedrag += float(bedrag)
            if self.afgelost_bedrag >= self.origineel_bedrag:
                self.status = "betaald"
            afl_nummers.append(datum)
            self.aflossingen = ",".join(afl_nummers)
            self.save()
            return True
        else:
            return False


class LidgeldKlasse(models.Model):
    naam = models.CharField(max_length=20)
    lidgeld = models.IntegerField()
    objects = models.Manager()

    def __str__(self):
        return self.naam

donza/management/forms.py
from django import forms
from itertools import chain

from .models import Lid, Ouder, Ploeg


class LidForm(forms.ModelForm):

    # Define the queryset for the familieleden selector
    def __init__(self, *args, **kwargs):
        super(LidForm, self).__init__(*args, **kwargs)
        if 'instance' in kwargs:
            lid = kwargs['instance']
            queryset = Lid.objects.extra(
                select={'sort': 'SELECT CASE WHEN familienaam = %s THEN 0 ELSE 1 END'}, 
                select_params=(lid.familienaam,)
            ).exclude(club_id=lid.club_id).order_by('sort')
            self.fields['familieleden'].queryset = queryset

    class Meta:
        model = Lid
        exclude = ["updated_at", "created_at"]
        help_texts = {
            'functies': 'Houd de SHIFT-toets ingedrukt om meerdere functies te selecteren',
            'familieleden': 'Houd de SHIFT-toets ingedrukt om meerdere familieleden te selecteren',
        }
        widgets = {
            'voornaam': forms.TextInput(attrs={'placeholder': 'Voornaam'}),
            'familienaam': forms.TextInput(attrs={'placeholder': 'Familienaam'}),
            'geboortedatum': forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}),
            'straatnaam_en_huisnummer': forms.TextInput(attrs={'placeholder': 'e.g. Teststraat 123 Bus A'}),
            'postcode': forms.NumberInput(attrs={'placeholder': 'e.g. 9800'}),
            'gemeente': forms.TextInput(attrs={'placeholder': 'e.g. Deinze'}),
            'extra_informatie': forms.Textarea(attrs={'placeholder': 'Hier komt eventuele extra informatie'}),
        }


class OuderForm(forms.ModelForm):
    class Meta:
        model = Ouder
        exclude = ["ouder_id"]


class PloegForm(forms.ModelForm):
    class Meta:
        model = Ploeg
        exclude = ["ploeg_id"]
        help_texts = {
            'min_geboortejaar': 'Dit is (onder normale omstandigheden) het oudst dat een speler mag zijn voor deze leeftijdscategorie, laat leeg voor Seniorenploegen',
            'max_geboortejaar': 'Dit is (onder normale omstandigheden) het jongst dat een speler mag zijn voor deze leeftijdscategorie',
            'uitzonderings_geboortejaar': 'Dit is het jongst dat een speler kan zijn, uitzonderingsgevallen waarbij een speler een jaar hoger speelt meegerekend. Als er geen uitzonderingen mogelijk zijn, vul hetzelfde in als "min jaar"'
        }

management/visual/forms.py
from bootstrap_modal_forms.forms import BSModalForm
from django import forms

from ..models import Lid, Ouder, Ploeg

SHIFT_MEERDERE_OPTIES = (
    "Houd de SHIFT-toets ingedrukt om meerdere opties te selecteren"
)


class LidForm(forms.ModelForm):

    # Define the queryset for the familieleden selector
    def __init__(self, *args, **kwargs):
        super(LidForm, self).__init__(*args, **kwargs)
        if "instance" in kwargs:
            lid = kwargs["instance"]
            queryset = (
                Lid.objects.extra(
                    select={
                        "sort": "SELECT CASE WHEN familienaam = %s THEN 0 ELSE 1 END"
                    },
                    select_params=(lid.familienaam,),
                )
                .exclude(club_id=lid.club_id)
                .order_by("sort")
            )
            self.fields["familieleden"].queryset = queryset

    class Meta:
        model = Lid
        exclude = ["updated_at", "created_at", "uid"]
        help_texts = {
            "functies": SHIFT_MEERDERE_OPTIES,
            "familieleden": SHIFT_MEERDERE_OPTIES,
        }
        widgets = {
            "voornaam": forms.TextInput(attrs={"placeholder": "Voornaam"}),
            "familienaam": forms.TextInput(
                attrs={"placeholder": "Familienaam"}
            ),
            "geboortedatum": forms.DateInput(
                attrs={"placeholder": "YYYY-MM-DD"}
            ),
            "straatnaam_en_huisnummer": forms.TextInput(
                attrs={"placeholder": "e.g. Teststraat 123 Bus A"}
            ),
            "postcode": forms.NumberInput(attrs={"placeholder": "e.g. 9800"}),
            "gemeente": forms.TextInput(attrs={"placeholder": "e.g. Deinze"}),
            "extra_informatie": forms.Textarea(
                attrs={"placeholder": "Hier komt eventuele extra informatie"}
            ),
        }


class LidModalForm(BSModalForm):
    class Meta:
        model = Lid
        fields = [
            "voornaam",
            "familienaam",
            "straatnaam_en_huisnummer",
            "postcode",
            "gemeente",
            "geboortedatum",
            "gsmnummer",
            "email",
        ]


class OuderForm(forms.ModelForm):
    class Meta:
        model = Ouder
        exclude = ["ouder_id"]


class PloegForm(forms.ModelForm):
    class Meta:
        model = Ploeg
        exclude = ["ploeg_id"]
        help_texts = {
            "min_geboortejaar": "Dit is (onder normale omstandigheden) het oudst dat een speler mag zijn voor deze leeftijdscategorie, laat leeg voor Seniorenploegen",  # noqa: E501
            "max_geboortejaar": "Dit is (onder normale omstandigheden) het jongst dat een speler mag zijn voor deze leeftijdscategorie",  # noqa: E501
            "uitzonderings_geboortejaar": 'Dit is het jongst dat een speler kan zijn, uitzonderingsgevallen waarbij een speler een jaar hoger speelt meegerekend. Als er geen uitzonderingen mogelijk zijn, vul hetzelfde in als "min jaar"',  # noqa: E501
        }

management/templates/base.html
{% load static %}
<!DOCTYPE html>
{# djlint:on #}
<html lang="nl">
    <head>
        <title>
            {% block title %}
                LDP Donza
            {% endblock title %}
        </title>
        <link rel="shortcut icon"
              type="image/png"
              href="{% static 'management/images/logo.png' %}"/>
        <!-- Required meta tags -->
        <meta charset="utf-8"/>
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <!-- Bootstrap CSS -->
        <!-- CSS only -->
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous"/>
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext"
              rel="stylesheet"
              type="text/css"/>
        <!-- Own CSS -->
        <link rel="stylesheet"
              href="{% static 'management/css/style.css' %}"
              type="text/css"/>
        <!-- Fontawesome -->
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
              rel="stylesheet"/>
        <!-- Bulma -->
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css"/>
        <!-- Scripts -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
                integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
                crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script defer
                src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
        <script src="{% static 'management/js/script.js'%}"></script>
        <script src="{% static 'management/js/bulma.js' %}"></script>
        <script src="{% static 'management/js/nav.js' %}"></script>
        <script src="{% static 'management/js/slowlink.js' %}"></script>
        <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
        <meta charset="UTF-8"/>
        <meta name="description"
              content="LDP Donza internal management tooling"/>
        <meta name="keywords"
              content="Django, HTML, JS"/>
        <meta name="author"
              content="Tim Van Erum"/>
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0"/>
    </head>
    <body class="main">
        <!-- Header -->
        <section class="section">
            {% include "header.html" %}
        </section>
        <!-- this is the main content -->
        <section class="section">
            <div class="container">
                {% if messages %}
                    <div class="block">
                        <!-- Messages to inform the user -->
                        {% for message in messages %}
                            <div class="notification is-{{ message.tags }}">
                                <button class="delete"></button>
                                <strong>{{ message|safe }}</strong>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {% block content %}
                {% endblock content %}
            </div>
        </section>
        <!-- Footer -->
        <footer class="footer">
            <div class="content has-text-centered">
                <div class="row justify-content-between">
                    <div class="col-4">
                        <span class="text-muted text-uppercase">LDP Donza</span>
                    </div>
                    <div class="col-4">
                        <span class="float-right"><a href="{% url 'logout' %}">Logout</a></span
                            >
                        </div>
                    </div>
                </div>
                <div class="footer-copyright text-center py-3">© 2020 Copyright: Tim Van Erum</div>
            </footer>
            {% block customscripts %}
            {% endblock customscripts %}
        </body>
        <!-- place to keep the modals at the top-level -->
        {% block modals %}
        {% endblock modals %}
        {% include "slowmodal.html" %}
    </html>

management/templates/header.html
{% load static %}
{% load guardian_tags %}
<nav class="navbar is-fixed-top navbar-dark black"
     role="navigation"
     aria-label="main navigation">
    <!-- Brand & Collapse -->
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item"
               href="{% url 'management:index' %}">
                <img src="{% static 'management/images/logo_header.png' %}"
                     alt="Logo LDP Donza"
                     width="120"
                     height="80"/>
            </a>
            <a role="button"
               id="navbar-burger-id"
               class="navbar-burger"
               aria-label="menu"
               aria-expanded="false"
               data-target="navbarCollapse">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div id="navbar-menu-id"
             class="navbar-menu"
             id="navbarCollapse">
            <div class="navbar-start">
                <a class="navbar-item"
                   href="{% url 'management:index' %}">Home</a>
                {% if perms.management.view_lid %}
                    <a class="navbar-item slow-link"
                       data-url="{% url 'management:leden' %}">Leden</a
                        >
                    {% endif %}
                    {% if perms.management.view_betaling %}
                        <a class="navbar-item"
                           href="{% url 'management:betalingen' %}">Betalingen</a
                            >
                        {% endif %}
                        {% if perms.management.view_mails %}
                            <a class="navbar-item"
                               href="{% url 'management:mails' %}">Mails</a>
                        {% endif %}
                        {% if perms.management.view_functie %}<a class="navbar-item">Functies</a>{% endif %}
                    </div>
                    <div class="navbar-end">
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-item">Huidig seizoen: {{ current_seizoen.naam }}</a>
                            <div class="navbar-dropdown">
                                {% for seizoen in seizoenen %}
                                    <a class="navbar-item"
                                       href="{% url 'management:change_seizoen' seizoen.seizoen_id %}?next={{ request.path }}">{{ seizoen.naam }}</a
                                        >
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>

management/templates/slowmodal.html
<div class="modal"
     id="slowmodal">
    <div class="modal-background"></div>
    <div class="modal-card"
         role="document">
        <div class="modal-card-head">
            <h3 class="modal-card-title">Even geduld...</h3>
        </div>
        <section class="modal-card-body">
            <div class="content">
                <p>
                    Het laden van deze pagina neemt wat tijd in beslag wegens de grote hoeveelheid data die opgehaald
                    moet worden
                </p>
            </div>
        </section>
        <footer class="modal-card-foot">
            <progress class="progress is-small is-primary"
                      max="100">15%</progress>
        </footer>
    </div>
</div>