donza/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("management/", include("management.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    re_path(
        "",
        RedirectView.as_view(pattern_name="management:index", permanent=False),
    ),
]

management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path("leden/", views.LidTableView.as_view(), name="leden"),
    path("leden/<int:pk>/", views.LidEditView.as_view(), name="lid"),
    path(
        "leden/<int:pk>/verwijder", views.verwijder_lid, name="verwijder_lid"
    ),
    path(
        "lid_modal/<int:pk>/", views.LidModalView.as_view(), name="lid_modal"
    ),
    path("leden/verwerk/", views.verwerk_leden, name="verwerk_leden"),
    path("leden/nieuw/", views.LidNewView.as_view(), name="nieuw_lid"),
    path("ouder/new/", views.create_ouder, name="new_ouder"),
    path(
        "betalingen/stuur_mail/<int:pk>/",
        views.stuur_mail,
        name="betalingen_mail",
    ),
    path(
        "betalingen/her_mail/<int:pk>/",
        views.herinnering_mail,
        name="herinnering_mail",
    ),
    path(
        "betalingen/bevestiging/<int:pk>/",
        views.bevestig_mail,
        name="bevestig_mail",
    ),
    path("betalingen/", views.BetalingTableView.as_view(), name="betalingen"),
    path("mails/", views.MailView.as_view(), name="mails"),
    path("mails/groep_mail/", views.groep_mail, name="groep_mail"),
    path("fetch_mail/", views.fetch_mail, name="fetch_mail"),
    path(
        "change_seizoen/<int:pk>/", views.change_seizoen, name="change_seizoen"
    ),
    path("", views.IndexView.as_view(), name="index"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
app_name = "management"

handler500 = views.handler500

donza/management/forms.py
from django import forms
from itertools import chain

from .models import Lid, Ouder, Ploeg


class LidForm(forms.ModelForm):

    # Define the queryset for the familieleden selector
    def __init__(self, *args, **kwargs):
        super(LidForm, self).__init__(*args, **kwargs)
        if 'instance' in kwargs:
            lid = kwargs['instance']
            queryset = Lid.objects.extra(
                select={'sort': 'SELECT CASE WHEN familienaam = %s THEN 0 ELSE 1 END'}, 
                select_params=(lid.familienaam,)
            ).exclude(club_id=lid.club_id).order_by('sort')
            self.fields['familieleden'].queryset = queryset

    class Meta:
        model = Lid
        exclude = ["updated_at", "created_at"]
        help_texts = {
            'functies': 'Houd de SHIFT-toets ingedrukt om meerdere functies te selecteren',
            'familieleden': 'Houd de SHIFT-toets ingedrukt om meerdere familieleden te selecteren',
        }
        widgets = {
            'voornaam': forms.TextInput(attrs={'placeholder': 'Voornaam'}),
            'familienaam': forms.TextInput(attrs={'placeholder': 'Familienaam'}),
            'geboortedatum': forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}),
            'straatnaam_en_huisnummer': forms.TextInput(attrs={'placeholder': 'e.g. Teststraat 123 Bus A'}),
            'postcode': forms.NumberInput(attrs={'placeholder': 'e.g. 9800'}),
            'gemeente': forms.TextInput(attrs={'placeholder': 'e.g. Deinze'}),
            'extra_informatie': forms.Textarea(attrs={'placeholder': 'Hier komt eventuele extra informatie'}),
        }


class OuderForm(forms.ModelForm):
    class Meta:
        model = Ouder
        exclude = ["ouder_id"]


class PloegForm(forms.ModelForm):
    class Meta:
        model = Ploeg
        exclude = ["ploeg_id"]
        help_texts = {
            'min_geboortejaar': 'Dit is (onder normale omstandigheden) het oudst dat een speler mag zijn voor deze leeftijdscategorie, laat leeg voor Seniorenploegen',
            'max_geboortejaar': 'Dit is (onder normale omstandigheden) het jongst dat een speler mag zijn voor deze leeftijdscategorie',
            'uitzonderings_geboortejaar': 'Dit is het jongst dat een speler kan zijn, uitzonderingsgevallen waarbij een speler een jaar hoger speelt meegerekend. Als er geen uitzonderingen mogelijk zijn, vul hetzelfde in als "min jaar"'
        }

management/visual/forms.py
from bootstrap_modal_forms.forms import BSModalForm
from django import forms

from ..models import Lid, Ouder, Ploeg

SHIFT_MEERDERE_OPTIES = (
    "Houd de SHIFT-toets ingedrukt om meerdere opties te selecteren"
)


class LidForm(forms.ModelForm):

    # Define the queryset for the familieleden selector
    def __init__(self, *args, **kwargs):
        super(LidForm, self).__init__(*args, **kwargs)
        if "instance" in kwargs:
            lid = kwargs["instance"]
            queryset = (
                Lid.objects.extra(
                    select={
                        "sort": "SELECT CASE WHEN familienaam = %s THEN 0 ELSE 1 END"
                    },
                    select_params=(lid.familienaam,),
                )
                .exclude(club_id=lid.club_id)
                .order_by("sort")
            )
            self.fields["familieleden"].queryset = queryset

    class Meta:
        model = Lid
        exclude = ["updated_at", "created_at", "uid"]
        help_texts = {
            "functies": SHIFT_MEERDERE_OPTIES,
            "familieleden": SHIFT_MEERDERE_OPTIES,
        }
        widgets = {
            "voornaam": forms.TextInput(attrs={"placeholder": "Voornaam"}),
            "familienaam": forms.TextInput(
                attrs={"placeholder": "Familienaam"}
            ),
            "geboortedatum": forms.DateInput(
                attrs={"placeholder": "YYYY-MM-DD"}
            ),
            "straatnaam_en_huisnummer": forms.TextInput(
                attrs={"placeholder": "e.g. Teststraat 123 Bus A"}
            ),
            "postcode": forms.NumberInput(attrs={"placeholder": "e.g. 9800"}),
            "gemeente": forms.TextInput(attrs={"placeholder": "e.g. Deinze"}),
            "extra_informatie": forms.Textarea(
                attrs={"placeholder": "Hier komt eventuele extra informatie"}
            ),
        }


class LidModalForm(BSModalForm):
    class Meta:
        model = Lid
        fields = [
            "voornaam",
            "familienaam",
            "straatnaam_en_huisnummer",
            "postcode",
            "gemeente",
            "geboortedatum",
            "gsmnummer",
            "email",
        ]


class OuderForm(forms.ModelForm):
    class Meta:
        model = Ouder
        exclude = ["ouder_id"]


class PloegForm(forms.ModelForm):
    class Meta:
        model = Ploeg
        exclude = ["ploeg_id"]
        help_texts = {
            "min_geboortejaar": "Dit is (onder normale omstandigheden) het oudst dat een speler mag zijn voor deze leeftijdscategorie, laat leeg voor Seniorenploegen",  # noqa: E501
            "max_geboortejaar": "Dit is (onder normale omstandigheden) het jongst dat een speler mag zijn voor deze leeftijdscategorie",  # noqa: E501
            "uitzonderings_geboortejaar": 'Dit is het jongst dat een speler kan zijn, uitzonderingsgevallen waarbij een speler een jaar hoger speelt meegerekend. Als er geen uitzonderingen mogelijk zijn, vul hetzelfde in als "min jaar"',  # noqa: E501
        }

management/views.py
from datetime import datetime as datetime

from bootstrap_modal_forms.generic import BSModalReadView
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render, reverse
from django.template import loader
from django.views import generic
from django.views.generic.edit import FormView, UpdateView
from django_filters.views import FilterView
from django_tables2.views import MultiTableMixin, SingleTableMixin

from management.mail.group_mail import group_mail

from .mail.send_mail import bevestig_betaling, lidgeld_mail, send_herinnering
from .main.betalingen import genereer_betalingen, registreer_betalingen
from .main.ledenbeheer import import_from_csv, lid_update_uid
from .models import Betaling, Functie, Lid, Ploeg, PloegLid
from .resources import (
    CoachLidDownloadResource,
    create_general_workbook,
    create_team_workbook,
)

# Deze lijn moet er in blijven staan om de TeamSelector te kunnen laden
# noinspection PyUnresolvedReferences
from .utils import get_current_seizoen
from .visual.filters import LidFilter
from .visual.forms import LidForm, OuderForm, PloegForm
from .visual.tables import BetaaldTable, DraftTable, LidTable, VerstuurdTable

PERMISSION_DENIED = """
            Je hebt niet de juiste permissies om deze pagina te bekijken.
            Indien je dit wel nodig hebt, contacteer de webmaster.
            """

"""
Class based views
"""


class IndexView(generic.TemplateView):
    template_name = "management/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        aantal_leden = len(Lid.objects.all())
        aantal_spelers = len(
            PloegLid.objects.filter(
                functie__functie="Speler",
                ploeg__seizoen=get_current_seizoen(self.request),
            )
        )
        aantal_coaches = len(
            PloegLid.objects.filter(
                functie__functie="Coach",
                ploeg__seizoen=get_current_seizoen(self.request),
            )
        )
        aantal_pvn = len(
            PloegLid.objects.filter(
                functie__functie="Ploegverantwoordelijke",
                ploeg__seizoen=get_current_seizoen(self.request),
            )
        )
        aantal_ploegen = len(
            Ploeg.objects.filter(seizoen=get_current_seizoen(self.request))
        )
        aantal_betalingen = len(
            Betaling.objects.filter(seizoen=get_current_seizoen(self.request))
        )
        aantal_onbetaalde = len(
            Betaling.objects.filter(
                seizoen=get_current_seizoen(self.request)
            ).exclude(status="voltooid")
        )
        aantal_draft_betalingen = len(
            Betaling.objects.filter(
                seizoen=get_current_seizoen(self.request), status="draft"
            )
        )
        context_app = {
            "aantal_leden": aantal_leden,
            "aantal_spelers": aantal_spelers,
            "aantal_coaches": aantal_coaches,
            "aantal_pvn": aantal_pvn,
            "aantal_ploegen": aantal_ploegen,
            "aantal_betalingen": aantal_betalingen,
            "aantal_onbetaalde": aantal_onbetaalde,
            "aantal_draft_betalingen": aantal_draft_betalingen,
        }
        context = {**context, **context_app}
        return context


class LidNewView(FormView):
    template_name = "management/lid_edit.html"
    form_class = LidForm
    model = Lid

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ouderform"] = OuderForm
        return context

    def form_valid(self, form):
        nieuw_lid = form.save(commit=False)
        if not nieuw_lid.uid:
            lid_update_uid(nieuw_lid)
            nieuw_lid.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("management:leden")


class LidEditView(PermissionRequiredMixin, UpdateView):
    template_name = "management/lid_edit.html"
    template_name_suffix = ""
    form_class = LidForm
    model = Lid
    permission_required = ("management.change_lid",)
    permission_denied_message = PERMISSION_DENIED

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ouderform"] = OuderForm
        return context

    def form_invalid(self, form):
        messages.error(self.request, form.errors)
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse("management:leden")


class LidTableView(PermissionRequiredMixin, SingleTableMixin, FilterView):
    model = Lid
    table_class = LidTable
    template_name = "management/ledenbeheer.html"
    table_pagination = False
    filterset_class = LidFilter
    permission_required = ("management.view_lid",)
    permission_denied_message = PERMISSION_DENIED

    @staticmethod
    def post(request, *args, **kwargs):
        # retrieve the file from the request
        csv_file = request.FILES["file"]

        if not csv_file.name.endswith(".csv"):
            messages.error(request, "This is not a csv file")
            return redirect(reverse("management:leden"), permanent=True)

        import_from_csv(csv_file, request)
        messages.success(request, "Import van csv succesvol")

        return redirect(reverse("management:leden"), permanent=True)


class BetalingTableView(
    PermissionRequiredMixin, MultiTableMixin, generic.TemplateView
):
    model = Betaling
    permission_required = ("management.view_betaling",)
    template_name = "management/betalingen.html"
    permission_denied_message = PERMISSION_DENIED

    def get_tables(self):
        request = self.request
        seizoen = get_current_seizoen(request)
        draft_queryset = Betaling.objects.filter(
            status="draft", seizoen=seizoen
        ).all()
        verstuurd_queryset = Betaling.objects.filter(
            status="mail_sent", seizoen=seizoen
        ).all()
        betaald_queryset = Betaling.objects.filter(
            status="betaald", seizoen=seizoen
        ).all()
        return [
            DraftTable(draft_queryset, prefix="draft-"),
            VerstuurdTable(verstuurd_queryset, prefix="sent-"),
            BetaaldTable(betaald_queryset, prefix="betaald-"),
        ]

    @staticmethod
    def post(request, *args, **kwargs):
        # retrieve the file from the request
        csv_file = request.FILES["file"]
        if not csv_file.name.endswith(".csv"):
            messages.error(request, "This is not a csv file")
            return redirect(reverse("management:betalingen"))

        registreer_betalingen(csv_file, request)
        messages.success(request, "Inlezen van betalingen succesvol")

        return redirect(reverse("management:betalingen"))


class LidModalView(BSModalReadView):
    model = Lid
    template_name = "management/lid_modal.html"


class MailView(generic.TemplateView):
    template_name = "management/mailing.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["mail_template"] = "mail/intentiemail.html"
        return context


"""
Method based views
"""


def handler500(request, *args, **argv):
    response = render(request, "500.html", {}, status=500)
    return response


def genereer(request):
    if request.method == "POST":
        pks = request.POST.getlist("selection")
        geselecteerde_leden = Lid.objects.filter(pk__in=pks)
        seizoen = get_current_seizoen(request)
        # genereer de betalingen voor de geselecteerde leden
        genereer_betalingen(geselecteerde_leden, seizoen)

        messages.success(
            request, "Betalingen voor geselecteerde leden gegenereerd"
        )
        return redirect(reverse("management:leden"), permanent=True)
    else:
        raise Http404("Methode bestaat niet. Deze pagina is niet beschikbaar.")


def create_ouder(request):
    ouder_form = OuderForm(request.POST)
    redirect_path = request.POST.get("next")
    if ouder_form.is_valid():
        ouder_form.save()
    else:
        messages.add_message(request, messages.ERROR, ouder_form.errors)
    return redirect(redirect_path)


def create_ploeg(request):
    ploeg_form = PloegForm(request.POST)
    redirect_path = request.POST.get("next")
    if ploeg_form.is_valid():
        ploeg_form.save()
    else:
        messages.add_message(
            request, messages.ERROR, "Ongeldig formulier voor nieuwe ploeg"
        )
    return redirect(redirect_path)


def stuur_mail(_, pk):
    lidgeld_mail(pk)
    return redirect(reverse("management:betalingen"), permanent=False)


def herinnering_mail(_, pk):
    send_herinnering(pk)
    return redirect(reverse("management:betalingen"), permanent=False)


def bevestig_mail(request, pk):
    bevestig_betaling(pk, request)
    return redirect(reverse("management:betalingen"), permanent=False)


def verwijder_lid(_, pk):
    Lid.objects.get(pk=pk).delete()
    return redirect(reverse("management:leden"), permanent=False)


def verwijder_leden(request):
    if request.method == "POST":
        pks = request.POST.getlist("selection")
        geselecteerde_leden = Lid.objects.filter(pk__in=pks)

        geselecteerde_leden.all().delete()

        messages.success(request, "Geselecteerde leden verwijderd")
        return redirect(reverse("management:leden"), permanent=True)
    else:
        # no idea what to do here
        print("Test")
        pass


def verwerk_leden(request):
    if request.method == "POST":
        if "verwijder" in request.POST:
            return verwijder_leden(request)
        elif "genereer" in request.POST:
            return genereer(request)
        else:
            raise Http404("Action not found")
    else:
        # no idea what to do here
        print("Test")
        pass


def export_ploeg_csv(request, pk):
    """

management/templates/management/ledenbeheer.html
{% extends "base.html" %}
{% load static %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}
{% block title %}
    Ledenbeheer
{% endblock title %}
{% block content %}
    <div class="col">
        <div class="row mb-3 justify-content-center">
            <h1 class="title is-2">Ledenbeheer</h1>
        </div>
        <div class="row mb-3 pt-3 pb-3 border rounded">
            <div class="col-6">
                {% if filter %}
                    <form method="get"
                          class="form"
                          id="filter">
                        <div class="form-group row">
                            {% with field=filter.form.voornaam %}
                                <label class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                                <div class="col-sm-8">{{ field }}</div>
                            {% endwith %}
                        </div>
                        <div class="form-group row">
                            {% with field=filter.form.familienaam %}
                                <label class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                                <div class="col-sm-8">{{ field }}</div>
                            {% endwith %}
                        </div>
                        <div class="form-group row">
                            {% with field=filter.form.geboortedatum %}
                                <label class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                                <div class="col-sm-8 text-center">{{ field }}</div>
                            {% endwith %}
                        </div>
                        <div class="form-group row">
                            {% with field=filter.form.actief_lid %}
                                <label class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                                <div class="col-sm-8">{{ field }}</div>
                            {% endwith %}
                        </div>
                        <button class="btn btn-block btn-primary"
                                form="filter"
                                action="submit">Filter Resultaten</button>
                    </form>
                {% endif %}
            </div>
            <div class="col-6 float-right">
                <button type="submit"
                        form="verwerk"
                        class="btn btn-success btn-block mb-3"
                        value="Genereer"
                        name="genereer">
                    Genereer Betalingen
                </button>
                <a type="button"
                   class="btn btn-secondary btn-block mb-3"
                   href="{% url 'management:nieuw_lid' %}">Nieuw Lid</a>
                <form class="mb-3"
                      method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file"
                                   name="file"
                                   class="custom-file-input"
                                   id="inputGroupFile02"/>
                            <label class="custom-file-label"
                                   for="inputGroupFile02">Kies CSV-bestand</label>
                        </div>
                        <div class="input-group-append">
                            <button class="btn btn-secondary"
                                    type="submit">Upload</button>
                        </div>
                    </div>
                </form>
                <button type="submit"
                        form="verwerk"
                        class="btn btn-danger btn-block mb-3"
                        value="Verwijder"
                        name="verwijder">
                    Verwijder leden
                </button>
            </div>
        </div>
        <div class="row alert alert-secondary justify-content-center">
            <p>Voor meer informatie over een lid, klik op de rij.</p>
        </div>
        <div class="row justify-content-center">
            <form action="{% url 'management:verwerk_leden' %}"
                  method="post"
                  id="verwerk">
                {% csrf_token %}
                <div class="row">{% render_table table 'django_tables2/semantic.html' %}</div>
            </form>
        </div>
    </div>
{% endblock content %}
{% block customscripts %}
    <script src="{% static 'management/js/toggle.js'%}"></script>
{% endblock customscripts %}

management/templates/management/lid_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load bulma_tags %}
{% load static %}
{% block content %}
    <div class="mb-5">
        <h1 class="title is-2">
            Bewerk Lid
            {% if form.voornaam.value and form.familienaam.value %}
                ({{ form.voornaam.value }} {{ form.familienaam.value }})
            {% endif %}
        </h1>
    </div>
    <form method="post"
          class="post-form">
        {% csrf_token %}
        <!-- Algemene informatie -->
        <div class="tile box is-ancestor">
            <div class="tile is-vertical is-12">
                <div class="tile is-parent">
                    <div class="tile is-child">
                        <div class="mb-3">
                            <h4 class="title is-3">
                                <em class="fas fa-address-card"></em>
                                Algemene informatie
                                {% if lid %}
                                    <a class="btn btn-danger float-right"
                                       href="{% url 'management:verwijder_lid' lid.club_id %}">Verwijder lid</a>
                                {% endif %}
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="tile is-horizontal">
                    <div class="tile is-parent is-vertical is-4">
                        <div class="tile is-child">
                            <div class="field">{{ form.voornaam|bulma }}</div>
                            <div class="field">{{ form.familienaam|bulma }}</div>
                            <div class="field">{{ form.geslacht|bulma }}</div>
                        </div>
                    </div>
                    <div class="tile is-parent is-4 is-vertical">
                        <div class="tile is-child">
                            <div class="field">{{ form.geboortedatum|bulma }}</div>
                            <div class="field">{{ form.lidnummer_vbl|bulma }}</div>
                            <div class="field">{{ form.familieleden|bulma }}</div>
                        </div>
                    </div>
                    <div class="tile is-parent is-4 is-vertical">
                        <div class="tile is-child">
                            <div class="field">{{ form.sportief_lid|bulma }}</div>
                            <div class="field">{{ form.betalend_lid|bulma }}</div>
                            <div class="field">{{ form.gescheiden_ouders|bulma }}</div>
                            <div class="field">{{ form.facturatie|bulma }}</div>
                            <div class="field">{{ form.afbetaling|bulma }}</div>
                            <div class="field">{{ form.actief_lid|bulma }}</div>
                        </div>
                        <div class="tile is-child">
                            <div class="field">{{ form.vader|bulma }}</div>
                            <div class="field">{{ form.moeder|bulma }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Functies, Adres en Contactgegevens -->
        <div class="tile box is-ancestor">
            <div class="tile is-4">
                <div class="tile is-vertical is-12">
                    <div class="tile is-parent">
                        <div class="tile is-child">
                            <div class="mb-3">
                                <h4 class="title is-3">
                                    <em class="fas fa-user-friends"></em>
                                    Functies
                                </h4>
                            </div>
                        </div>
                    </div>
                    <div class="tile is-horizontal">
                        <div class="tile is-parent is-vertical is-12">
                            <div class="tile is-child">
                                <div class="field">{{ form.functies|bulma }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tile is-4">
                <div class="tile is-vertical is-12">
                    <div class="tile is-parent">
                        <div class="tile is-child">
                            <div class="mb-3">
                                <h4 class="title is-3">
                                    <em class="fas fa-map-pin"></em>
                                    Adres
                                </h4>
                            </div>
                        </div>
                    </div>
                    <div class="tile is-horizontal">
                        <div class="tile is-parent is-vertical is-12">
                            <div class="tile is-child">
                                <div class="field">{{ form.straatnaam_en_huisnummer|bulma }}</div>
                                <div class="field">{{ form.postcode|bulma }}</div>
                                <div class="field">{{ form.gemeente|bulma }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tile is-4">
                <div class="tile is-vertical is-12">
                    <div class="tile is-parent">
                        <div class="tile is-child">
                            <div class="mb-3">
                                <h4 class="title is-3">
                                    <em class="fas fa-map-pin"></em>
                                    Contactgegevens
                                </h4>
                            </div>
                        </div>
                    </div>
                    <div class="tile is-horizontal">
                        <div class="tile is-parent is-vertical is-12">
                            <div class="tile is-child">
                                <div class="field">{{ form.gsmnummer|bulma }}</div>
                                <div class="field">{{ form.email|bulma }}</div>
                                <div class="field">{{ form.rekeningnummer|bulma }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Extra informatie -->
        <div class="tile box is-ancestor">
            <div class="tile is-vertical is-12">
                <div class="tile is-parent">
                    <div class="tile is-child">
                        <div class="mb-3">
                            <h4 class="title is-3">
                                <em class="fas fa-signature"></em>
                                Extra informatie
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="tile is-parent is-12">
                    <div class="tile is-child">
                        {{ form.extra_informatie|bulma }}
                    </div>
                </div>
                <div class="tile is-parent is-12">
                    <div class="tile is-child">
                        <div class="control">
                            <button type="submit"
                                    class="save button is-success is-light">
                                Opslaan
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}